import jsPDF from "jspdf";
import autotable from "jspdf-autotable";

const LOGO_TEXT = "AERIS";

const formatDateTime = () => {
  const now = new Date();
  return now.toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

const headerTemplate = (doc, city) => {
  doc.setFillColor(4, 15, 24);
  doc.rect(10, 10, 190, 30, "F");
  doc.setFontSize(14);
  doc.setTextColor("#00C2B8");
  doc.setFont("helvetica", "bold");
  doc.text(LOGO_TEXT, 15, 28);
  doc.setFontSize(10);
  doc.setTextColor("#E2EEF8");
  doc.text("AI-Powered Air Quality Intelligence & Decision Support Platform", 55, 18);
  doc.setTextColor("#7BA5C4");
  doc.setFontSize(9);
  doc.text(`Generated: ${formatDateTime()}`, 55, 26);
  doc.setFontSize(12);
  doc.setTextColor("#FFFFFF");
  doc.text(`City: ${city}`, 155, 22, { align: "right" });
};

const footerTemplate = (doc, pageNumber, totalPages) => {
  const y = doc.internal.pageSize.height - 15;
  doc.setFontSize(8);
  doc.setTextColor("#7BA5C4");
  doc.text(`Generated by AI-Powered Air Quality Intelligence & Decision Support Platform`, 14, y);
  doc.text(`Page ${pageNumber} of ${totalPages}`, 195, y, { align: "right" });
};

const pageContent = (doc, city, pageNumber, totalPages) => {
  headerTemplate(doc, city);
  footerTemplate(doc, pageNumber, totalPages);
};

const finalizeDocument = (doc, city) => {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i += 1) {
    doc.setPage(i);
    pageContent(doc, city, i, pages);
  }
  return doc;
};

export function createAerisReport(reportData) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const city = reportData.city || "Unknown City";
  const pageWidth = doc.internal.pageSize.width;
  const contentTop = 52;

  const items = [
    ["Project Title", reportData.title || "Aeris Environmental Intelligence Report"],
    ["Date", reportData.date],
    ["Time", reportData.time],
    ["Selected City", reportData.city],
    ["AQI", reportData.aqi],
    ["AQI Category", reportData.category],
    ["Primary AQI Driver", reportData.primaryDriver],
    ["Dominant Pollutant", reportData.dominantPollutant],
    ["Pollution Sources", reportData.pollutionSources],
    ["Environmental Risk Score", reportData.riskScore],
    ["Health Recommendations", reportData.healthRecommendation],
    ["Decision Support", reportData.decisionSupport],
    ["Weather Conditions", reportData.weatherSummary],
    ["Forecast Summary", reportData.forecastSummary],
  ];

  const createTextBlock = (title, value, y) => {
    doc.setFontSize(10);
    doc.setTextColor("#7BA5C4");
    doc.text(title, 30, y);
    doc.setFontSize(11);
    doc.setTextColor("#E2EEF8");
    doc.text(value || "—", 30, y + 14);
  };

  const addSectionBreak = (y, label) => {
    doc.setFillColor(3, 13, 24);
    doc.rect(30, y - 6, pageWidth - 60, 24, "F");
    doc.setFontSize(10);
    doc.setTextColor("#00C2B8");
    doc.text(label, 36, y + 10);
    return y + 28;
  };

  pageContent(doc, city, 1, 1);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor("#FFFFFF");
  doc.text("Aeris Environmental Intelligence Report", pageWidth / 2, 44, { align: "center" });

  let y = contentTop;
  y = addSectionBreak(y, "Core Summary");
  doc.setFont("helvetica", "normal");
  items.slice(0, 6).forEach(([label, value], index) => {
    createTextBlock(label, value, y);
    y += 32;
  });

  y += 14;
  y = addSectionBreak(y, "Environmental Analysis");
  items.slice(6, 12).forEach(([label, value], index) => {
    createTextBlock(label, value, y);
    y += 32;
  });

  const tableStart = y + 14;
  autotable(doc, {
    startY: tableStart,
    head: [["Nearby Cleanest Areas", "AQI", "Nearby Most Polluted Areas", "AQI"]],
    body: Array.from({ length: Math.max(reportData.cleanestAreas.length, reportData.pollutedAreas.length) }).map((_, idx) => [
      reportData.cleanestAreas[idx]?.name || "—",
      reportData.cleanestAreas[idx]?.aqi || "—",
      reportData.pollutedAreas[idx]?.name || "—",
      reportData.pollutedAreas[idx]?.aqi || "—",
    ]),
    headStyles: { fillColor: [0, 194, 184], textColor: 255, halign: "center" },
    bodyStyles: { textColor: 226, fontSize: 9, halign: "center" },
    styles: { fillColor: [7, 21, 38], lineColor: [28, 49, 74], lineWidth: 0.5 },
    theme: "grid",
  });

  const finalY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 24 : tableStart + 120;
  if (finalY + 110 > doc.internal.pageSize.height) {
    doc.addPage();
    pageContent(doc, city, 2, 2);
  }

  const footerY = doc.internal.pageSize.height - 60;
  doc.setFontSize(10);
  doc.setTextColor("#7BA5C4");
  doc.text("Generated by AI-Powered Air Quality Intelligence & Decision Support Platform", 30, footerY);
  doc.text(`Page ${doc.internal.getNumberOfPages()}`, pageWidth - 30, footerY, { align: "right" });

  return finalizeDocument(doc, city);
}

const safeCsvValue = (value) => {
  if (value == null) return "";
  if (Array.isArray(value)) return value.join("; ");
  return String(value).replace(/\n/g, " ").replace(/"/g, '""');
};

export function exportReportCsv(reportData) {
  const rows = [
    ["Field", "Value"],
    ["Project Title", safeCsvValue(reportData.title)],
    ["Date", safeCsvValue(reportData.date)],
    ["Time", safeCsvValue(reportData.time)],
    ["Selected City", safeCsvValue(reportData.city)],
    ["AQI", safeCsvValue(reportData.aqi)],
    ["AQI Category", safeCsvValue(reportData.category)],
    ["Primary AQI Driver", safeCsvValue(reportData.primaryDriver)],
    ["Dominant Pollutant", safeCsvValue(reportData.dominantPollutant)],
    ["Pollution Sources", safeCsvValue(reportData.pollutionSources)],
    ["Environmental Risk Score", safeCsvValue(reportData.riskScore)],
    ["Health Recommendations", safeCsvValue(reportData.healthRecommendation)],
    ["Decision Support", safeCsvValue(reportData.decisionSupport)],
    ["Weather Conditions", safeCsvValue(reportData.weatherSummary)],
    ["Forecast Summary", safeCsvValue(reportData.forecastSummary)],
  ];
  if (reportData.cleanestAreas || reportData.pollutedAreas) {
    rows.push(["", ""]);
    rows.push(["Nearby Cleanest Areas", "AQI", "Nearby Most Polluted Areas", "AQI"]);
    const length = Math.max(reportData.cleanestAreas?.length || 0, reportData.pollutedAreas?.length || 0);
    for (let i = 0; i < length; i += 1) {
      rows.push([
        safeCsvValue(reportData.cleanestAreas?.[i]?.name),
        safeCsvValue(reportData.cleanestAreas?.[i]?.aqi),
        safeCsvValue(reportData.pollutedAreas?.[i]?.name),
        safeCsvValue(reportData.pollutedAreas?.[i]?.aqi),
      ]);
    }
  }

  const csv = rows.map((row) => row.map((cell) => `"${cell}"`).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  return { url, filename: `${reportData.city || "Environmental_Report"}.csv` };
}
